config/routes.rb
EDesign::Application.routes.draw do
     resources :orders
  devise_for :users

  resources :plans do
     resources :orders
   end

  resources :pages
  get "pages/home"

  get "pages/about"

  get "pages/contact"
  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/purchase_info', :to => 'pages#purchase_info'
  match '/contact', :to => 'pages#contact'
  match '/custom_mods', :to => 'pages#custom_mods'
  match '/questions', :to => 'pages#questions'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :plan_id, :user_id, :stripe_card_token, :plan_cost
  attr_accessor :stripe_card_token, :plan_cost
  belongs_to :plan
  belongs_to :user
  accepts_nested_attributes_for :plan
  
  def save_with_payment
      
      @amount = (self.plan.price * self.plan.sqfoot * 100).to_i  
      
      if valid?
          charge = Stripe::Charge.create(amount: @amount, currency: 'usd', card: stripe_card_token)
       
          save!
      end
      rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating customer: #{e.message}"
      errors.add :base, "There was a problem with your credit card."
      false
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_filter :authenticate_user!  
    #before_filter :get_course

      def new
          @plan = Plan.find(params[:plan_id])
          @order = @plan.orders.new

      end
      def show

          @order = Order.find(params[:id])
      end
      def index
          authorize! :index, @user, :message => 'Not authorized as an administrator.'
      	  if params[:search]
              @orders = Order.search(params[:search]).paginate(:page => params[:page], :per_page => 5)       
            else
          @orders = Order.paginate(:page => params[:page], :per_page => 5)
          end
          @title = "Orders"
      end

      def create

          @order = Order.new(params[:order])
          if @order.save_with_payment
              redirect_to @order, :notice => "Thank you for your purchase!  Enjoy your Class!"
              else
              render :new
          end
      end

      # GET /courses/1/edit
      def edit
          @order = Order.find(params[:id])
      end

      # PUT /courses/1
      # PUT /courses/1.json
      def update
          @order = Order.find(params[:id])

          respond_to do |format|
              if @order.update_attributes(params[:order])
                  format.html { redirect_to @order, notice: 'Course was successfully updated.' }
                  format.json { head :no_content }
                  else
                  format.html { render action: "edit" }
                  format.json { render json: @order.errors, status: :unprocessable_entity }
              end
          end
      end

      # DELETE /courses/1
      # DELETE /courses/1.json
      def destroy
          @order = Order.find(params[:id])
          @order.destroy

          respond_to do |format|
              format.html { redirect_to orders_url }
              format.json { head :no_content }
          end
      end

  end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
<%= f.hidden_field :stripe_card_token %>
<%= f.hidden_field :plan_id %>
<%= f.hidden_field :user_id, :value => current_user.id %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>

<div id="stripe_error">
  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
</div>
<div class="actions">
	<%= f.submit "Purchase Now", class: "btn btn-large btn-primary" %>
</div>	

<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>User</th>
    <th>Plan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.user_id %></td>
    <td><%= order.plan_id %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<center><h1>New order | <%= @order.plan.name %> | Amount: $<%= @order.plan.price * @order.plan.sqfoot %></h1></center>

<%= render 'form' %>

<div class="span6">
	<ul>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "What Does My Purchase Include?", "/purchase_info" %></h4>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "Frequently Asked Questions", "/questions" %></h4>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "What If I Want To Make Custom Modificatons To The Plan?", "/custom_mods" %></h4><br />
		
	</ul>
</div>
<div class="span12">

<%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Thank you for your purchase of <%= @order.plan.name %></h1>

<p>
  <b>Plan:</b>
  <%= @order.plan.name %>
</p>
<p>Please allow 3-4 days for us to print out the architectural drawings and ship them to you.</p>
<p>If you have any questions at all please feel free to contact Rick Remore at <%= mail_to "plans@venturefour.com", "plans@venturefour.com" %> or (512) 328-8581.</p>
	
<p><%= link_to "Back to Plans", plans_path %></p>	

<%#<%= link_to 'Edit', edit_order_path(@order) %> 
<%#<%= link_to 'Back', orders_path %>