config/routes.rb
EDesign::Application.routes.draw do
     resources :orders
  devise_for :users

  resources :plans do
     resources :orders
   end

  resources :pages
  get "pages/home"

  get "pages/about"

  get "pages/contact"
  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/purchase_info', :to => 'pages#purchase_info'
  match '/contact', :to => 'pages#contact'
  match '/custom_mods', :to => 'pages#custom_mods'
  match '/questions', :to => 'pages#questions'

end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id                     :integer          not null, primary key
#  bedrooms               :integer
#  sqfoot                 :integer
#  levels                 :integer
#  bathrooms              :integer
#  price                  :decimal(, )
#  name                   :string(255)
#  half_bath              :integer
#  living                 :integer
#  suite                  :string(255)
#  stories                :string(255)
#  dining                 :integer
#  view                   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  drawing_1_file_name    :string(255)
#  drawing_1_content_type :string(255)
#  drawing_1_file_size    :integer
#  drawing_1_updated_at   :datetime
#  drawing_2_file_name    :string(255)
#  drawing_2_content_type :string(255)
#  drawing_2_file_size    :integer
#  drawing_2_updated_at   :datetime
#  elevation_file_name    :string(255)
#  elevation_content_type :string(255)
#  elevation_file_size    :integer
#  elevation_updated_at   :datetime
#  garage                 :integer
#  width                  :string(255)
#  depth                  :string(255)
#

class Plan < ActiveRecord::Base
  attr_accessible :garage, :bathrooms, :bedrooms, :dining, :half_bath, :levels, :living, :name, :price, :sqfoot, :stories, :suite, :view,
  :drawing_1_file_name, :drawing_1_content_type, :drawing_1_file_size, :drawing_1_updated_at, :drawing_2_file_name, :drawing_2_content_type,
  :drawing_2_file_size, :drawing_2_updated_at, :elevation_file_name, :elevation_content_type, :elevation_file_size, :elevation_updated_at,
  :drawing_1, :drawing_2, :elevation, :width, :depth, :garage_loc, :casita2, :media2,  :study2, :style, :court2
  has_attached_file :drawing_1,  :styles => { :full => ["2400x2400>", :jpg], :preview => ["365x365>", :jpg], :thumb => ["150x150>", :jpg] }
  has_attached_file :drawing_2,  :styles => { :full => ["2400x2400>", :jpg], :preview => ["365x365>", :jpg], :thumb => ["150x150>", :jpg] }
  has_attached_file :elevation,  :styles => { :full => ["2400x2400>", :jpg], :preview => ["365x365>", :jpg], :thumb => ["150x150>", :jpg] }
  has_many :orders, :dependent => :destroy
  has_many :users, through: :orders                 

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  # GET /plans
  # GET /plans.json
  def index

    @q = Plan.search(params[:q])
    @plans = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erbs
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @plan = Plan.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for @plan, :html => { :multipart => true } do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row-one span3">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sqfoot %>
    <%= f.number_field :sqfoot %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %>
    <%= f.select(:bedrooms, [['1', 1], ['2', 2],['3', 3],['4', 4],['5', 5],['6+', 6]],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %>
    <%= f.select(:bathrooms, [['1', 1], ['2', 2],['3', 3],['4', 4],['5', 5],['6+', 6]],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :depth %>
    <%= f.text_field :depth %>
  </div>
  <div class="field">
   <%= f.label :media2, "Plan has a Media Room" %>
    <%= f.select(:media2, [['Yes', 'Yes']],{ :prompt => "Not Sure"}) %>
    </div>
      <div class="field">
    <%= f.label :court2, "Plan has a Courtyard" %>
    <%= f.select(:court2, [['Yes', 'Yes']],{ :prompt => "Not Sure"}) %><br /><br /><br />
    </div>
</div>
<div class="row-two span3">
  <div class="field">
    <%= f.label :half_bath %>
    <%= f.select :half_bath, options_for_select([[''],['1', 1], ['2', 2],['3+', 3]]), :class => 'select_field' %>
  </div>
  <div class="field">
    <%= f.label :living %>
    <%= f.select(:living, [['1', 1], ['2', 2],['3', 3],['4+', 4]],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :dining %>
    <%= f.select(:dining, [['1', 1], ['2', 2],['3', 3],['4+', 4]],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
	<%= f.label :garage, "Number of Garages" %>
	<%= f.select(:garage, [['0', 1],['1', 2], ['2', 3],['3', 4],['4+', 5]],{ :prompt => "Not Sure"}) %>
	</div>
	<div class="field">
    <%= f.label :width %>
    <%= f.text_field :width %>
  	</div>
  <div class="field">
    <%= f.label :study2, "Plan has a Study" %>
    <%= f.select(:study2, [['Yes', 'Yes']],{ :prompt => "Not Sure"}) %>
    </div>
      <div class="field">
    <%= f.label :garage_loc, "Garage Location" %>
    <%= f.select(:garage_loc, [['Side', 'Side'],['front', 'front'],['detached', 'detached']],{ :prompt => "Not Sure"}) %>
    </div>
</div>
	<div class="row-three span3">
  <div class="field">
    <%= f.label :stories, "Levels" %>
    <%= f.select(:stories, [['Single-Story', 1], ['Multi-Story', 2],['Upside-Down', 'Upside-Down'],['Walk Out Basement', 'Walk Out Basement']],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :suite, "Owner's Suite Location" %>
    <%= f.select(:suite, [['Primary Level', 2],['Secondary Level', 3]],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :view, "View" %>
    <%= f.select(:view, [['Front View 1st Floor', 'Front View 1st Floor'], ['Front View 2nd Floor', 'Front View 2nd Floor'],['Rear View 1st Floor', 'Rear View 1st Floor'],['Rear View 2nd Floor', 'Rear View 2nd Floor']],{ :prompt => "Not Sure"}) %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.select(:price, [['0.75', 0.75],['0.90', 0.90],['1.05', 1.05],['1.20', 1.20]]) %>
  </div>
  <div class="field">
<%= f.label :style %>
    <%= f.select(:style, [['Hill country', 'Hill country'],[' Hill country modern', 'Hill country modern'],['Modern', 'Modern'],['Craftsman', 'Craftsman'],['Texas Tuscan', 'Texas Tuscan'],['Mediterranean', 'Mediterranean'],['Spanish', 'Spanish'],['Contemporary', 'Contemporary'],['French', 'French'],['French Country', 'French Country'],['Beach', 'Beach'],['Cottage', 'Cottage'],['Barn', 'Barn'],['traditional', 'traditional']],{ :prompt => "Not Sure"}) %>
  </div>
        <div class="field">
    <%= f.label :casita2, "Plan has a Casita" %>
    <%= f.select(:casita2, [['Yes', 'Yes']],{ :prompt => "Not Sure"}) %>
    </div>
</div>
<div class="row-four span2">
  <div class="control-group">
	   <%= f.label :drawing_1, "Upload Primary Plan PDF", :class => 'control-label' %>
<%= f.file_field :drawing_1 %>
  </div>
  <div class="control-group">
	   <%= f.label :drawing_2, "Upload SecondaryPlan PDF (optional)", :class => 'control-label' %>
<%= f.file_field :drawing_2 %>
  </div>
  <div class="control-group">
	   <%= f.label :elevation, "Upload Elevation PDF", :class => 'control-label' %>
<%= f.file_field :elevation %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
</div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<script>function moveScroller() {
    var move = function() {
        var st = $(window).scrollTop();
        var ot = $("#scroller-anchor").offset().top;
        var s = $("#scroller");
        if(st > ot) {
            s.css({
                position: "fixed",
                top: "0px"
            });
        } else {
            if(st <= ot) {
                s.css({
                    position: "relative",
                    top: ""
                });
            }
        }
    };
    $(window).scroll(move);
    move();
}
</script>
<div class="searchheading">
<h2>Advanced Plan Search</h2><br />
</div>
<div class="border span11"><p></div><br /><br />

	<div id="sidebar"> 
	  <div id="scroller-anchor"></div> 
	  <div id="scroller" style="margin-top:10px; width:960px"> 


<%= search_form_for @q do |f| %>
<div class="searchfield span3">
<%= f.label :sqfoot_gteq, "Square Footage Min" %>
<%= f.text_field :sqfoot_gteq %>
<%= f.label :sqfoot_lteq, "Square Footage Max" %>
<%= f.text_field :sqfoot_lteq %>

<%= f.label :bedrooms_eq, "Bedrooms" %>
<%= f.select(:bedrooms_eq, [['Not Sure', ''],['1', 1], ['2', 2],['3', 3],['4', 4],['5', 5],['6+', 6]]) %>
                                

  <%= f.label :bathrooms_eq, "Bathrooms" %>
<%= f.select(:bathrooms_eq, [['Not Sure', ''],['1', 1], ['2', 2],['3', 3],['4+', 4]]) %>


	  <%= f.label :half_bath_eq, "Half-Bathrooms" %>
	<%= f.select(:half_bath_eq, [['Not Sure', ''],['1', 1], ['2', 2],['3+', 3]]) %>
</div>
<div class="searchfield2 span2">

	<%= f.label :living_eq, "Living Areas" %>
	<%= f.select(:living_eq, [['Not Sure', ''],['1', 1], ['2', 2],['3', 3],['4+', 4]]) %>	
	
	<%= f.label :dining_eq, "Dining Areas" %>
	<%= f.select(:dining_eq, [['Not Sure', ''],['1', 1], ['2', 2],['3', 3],['4+', 4]]) %>
	
	<%= f.label :garage_eq, "Number of Garages" %>
	<%= f.select(:garage_eq, [['Not Sure', ''],['0', 1],['1', 2], ['2', 3],['3', 4],['4+', 5]]) %>

	
	<%= f.label :stories_eq, "Levels/Design" %>
	<%= f.select(:stories_eq, [['Not Sure', ''],['Single-Story', 1], ['Multi-Story', 2],['Upside-Down', 'Upside-Down'],['Walk Out Basement', 'Walk Out Basement']]) %>
	
	<%#<%= f.label :view_eq, "View" %>
    <%#<%= f.select(:view_eq, [['Front View 1st Floor', 1], ['Front View 2nd Floor', 2],['Rear View 1st Floor', 3],['Rear View 2nd Floor', 4]],{ :prompt => "Not Sure"}) %>
	
	<%= f.label :suite_eq, "Owners' Suite" %>
	<%= f.select(:suite_eq, [['Not Sure', ''],['Primary Level', 1],['Secondary Level', 2]]) %>
	
	<%= f.label :name_cont, "Search for Plan" %>
	<%= f.text_field :name_cont %>
<p>
  <%= f.submit class: "btn btn-primary" %>

<%= link_to "Start Over", plans_path, class: "btn btn-primary" %>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= link_to 'New Plan', new_plan_path, class: "btn btn-large btn-primary" %><br /><br /></p><br /><br /><br />
<% end %>
<% end %>
</div>

<% end %>
  </div>
</div>
<script type="text/javascript"> 
  $(function() {
    moveScroller();
  });
</script>

<center><p><b><red><%= @plans.count %> Plans Match Your Criteria</red></b></p></center>
<div class="pagination-right">
<%= will_paginate @plans %>
</div>
    <% @plans.each do |plan| %>
<div class="image span6">
	
<%= link_to image_tag(plan.drawing_1.url(:full)), plan_path(plan) %>
<dl class="dl-vertical">
	<p>
	  <b>Bedrooms:</b>
	  <%= plan.bedrooms %> |
	  <b>Sqfoot:</b>
	  <%= plan.sqfoot %> |
	  <b>Levels:</b>
	  <%= plan.stories %> |
	  <b>Bathrooms:</b>
	  <%= plan.bathrooms %>
	<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
	<%= link_to 'Delete', plan, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
<% end %>
	</p>

</div>
<% end %>
<div class="pagination-right span11">
<%= will_paginate @plans %>
</div>
<br />
<% if user_signed_in? %>
<% if current_user.has_role? :admin %>
<div class="new-button span12">
<%= link_to 'New Plan', new_plan_path, class: "btn btn-large btn-primary" %><br /><br />
</div>
<% end %>
<% end %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>
<div class="row-five span12">
<%= link_to 'Back', plans_path, class: "btn btn-large btn-primary" %><br /><br />
</div>

app/views/plans/show.html.erb
<script src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
<script>

$(document).ready(function() {


	$('#first').click(function(e){
		e.preventDefault();
		$('#picture').html($('#first').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);
});

$('#elevation').click(function(e){
	e.preventDefault();
		$('#picture').html($('#elevation').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});

$('#second').click(function(e){
	e.preventDefault();
		$('#picture').html($('#second').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image2').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});

$('#image2').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image2').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image5').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image5').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image3').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image3').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image4').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image4').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image7').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image7').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image8').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image8').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image9').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image9').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image10').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image10').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
$('#image11').click(function(e){
	e.preventDefault();
		$('#picture').html($('#image11').html());
		$('#picture').show('slide', {
			direction: "left"

		}, 2000);


});
	});

</script>

<script>
$(document).ready(function() {
$( "#up" ).click(function() {
  $( "#firstgroup" ).toggle( "slow") 
  $("#secondgroup").toggle("slow")

	});
$( "#down" ).click(function() {
  $( "#firstgroup" ).toggle( "slow") 
  $("#secondgroup").toggle("slow")

	});
$( "#down2" ).click(function() {
  $( "#secondgroup" ).toggle( "slow") 
  $("#thirdgroup").toggle("slow")

	});
$( "#up2" ).click(function() {
  $( "#secondgroup" ).toggle( "slow") 
  $("#thirdgroup").toggle("slow")

	});
});
</script>

<p id="notice"><%= notice %></p>


<div id="plan" class="span9">
<div id="picture">
<center><%= image_tag(@plan.drawing_1.url(:full)) %></center>
</div>

<center>
<br /><br />

		<% unless @plan.name.blank? %>
		<p>
		  <b>Name:</b>
		  <%= @plan.name %> |

		<% end %>

		  <b>Sqfoot:</b>
		  <%= @plan.sqfoot %> |

		  <b>Bedrooms:</b>
		  <%= @plan.bedrooms %> |

		  <b>Bathrooms:</b>
		  <%= @plan.bathrooms %> |

			<% unless @plan.half_bath.blank? %>

		  <b>Half bath:</b>
		  <%= @plan.half_bath %> 

			<% end %>

		<p>
		  <b>Living:</b>
		  <%= @plan.living %> |

		  <b>Dining:</b>
		  <%= @plan.dining %> |

		  <b>Levels:</b>
		  <%= @plan.stories %>

		<% unless @plan.view.blank? %>

		  <b>View:</b>
		  <%= @plan.view %> |

		<% end %>
		<% unless @plan.width.blank? %>

		  <b>Width:</b>
		  <%= @plan.width %> |

		<% end %>
		<% unless @plan.depth.blank? %>

		  <b>Depth:</b>
		  <%= @plan.depth %> 

		<% end %>

	</center>
		
		</p><br />
<div id="purchase" class="span2">
<% if @plan.price.blank? %>
<center><p><b>Price: $<%= (0.75 * @plan.sqfoot).to_i %></b> <%= link_to "Purchase new_plan_saved_plan_path!", new_plan_order_path(@plan), class: "btn btn-primary btn-lg" %></center></p>
<% else %>
<center><p><b>Price: $<%= (@plan.price * @plan.sqfoot).to_i %></b></p><p> <%= link_to "Purchase Plan!", new_plan_order_path(@plan), class: "btn btn-primary btn-lg"   %></center></p><br />
<% end %>

</div>


<div class="span6">
	<ul>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "What Does My Purchase Include?", "/purchase_info" %></h4>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "Frequently Asked Questions", "/questions" %></h4>
		<h4><i class="purchase-icon fa fa-star"></i> <%= link_to "What If I Want To Make Custom Modificatons To The Plan?", "/custom_mods" %></h4><br />
		
	</ul>
</div>

			
</div>	

<div id="sidebar_show" class="well span2">
	
<center><%= link_to "Purchase Plan!", new_plan_order_path(@plan), class: "btn btn-primary" %></center><br />
<p></p>

<div id="pics">
		<div id="first">
		<center><%= image_tag(@plan.drawing_1.url(:full)) %><center>

	</div>
</div>
<% unless @plan.drawing_2.blank? %>
<div id="pics">
			<div id="second">
			<center><%= image_tag(@plan.drawing_2.url(:full)) %></center>
		</div>
</div>
<% end %>
<div id="pics">
			<div id="elevation">
			<center><%= image_tag(@plan.elevation.url(:full)) %></center>
		</div>
</div>

<center><%= link_to "Purchase Plan!", new_plan_order_path(@plan), class: "btn btn-primary" %></center><br />
<back>
	<center><p><INPUT Type="button" class="btn btn-primary" VALUE="Back To Search" onClick="history.go(-1);return true;"></p></center><br />
	</back>
	<br />
</div>

<div class="buttons span12">

	<% if user_signed_in? %>
		<% if current_user.has_role? :admin %>
		<%= link_to 'Edit', edit_plan_path(@plan), class: "btn btn-large btn-primary" %> 
		<%= link_to 'New Plan', new_plan_path, class: "btn btn-large btn-primary" %> <br />

		<% end %>
	<% end %>

	<br /><br /><br /><br />
</div>